version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: ghost-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db_volume:/var/lib/postgresql/data
    networks:
      - common-net

  server:
    container_name: ghost-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: ${SERVER_PORT}
      DB_HOST: ghost-postgres
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
    ports:
      - "${SERVER_PORT}:9000"
    depends_on:
      - database
    networks:
      - common-net

volumes:
  db_volume:

networks:
  common-net: {}
