version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: ghost-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db_volume:/var/lib/postgresql/data

  server:
    container_name: ghost-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: ${SERVER_PORT}
      DB_HOST: ghost-postgres
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
    ports:
      - "${SERVER_PORT}:9000"
    depends_on:
      database:
        condition: service_healthy
        restart: true

  client:
    container_name: ghost-client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      PORT: ${CLIENT_PORT}
      SERVER_HOST: ghost-server
    ports:
      - "${CLIENT_PORT}:3000"
    depends_on:
      - server

volumes:
  db_volume:
