FROM golang:1.23 as builder

WORKDIR /build

COPY . .

RUN CGO_ENABLED=0 go build -o main cmd/api/main.go

FROM gcr.io/distroless/static-debian12 

WORKDIR /app
COPY --from=builder /build/main ./main

CMD ["/app/main"]